version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai  

  memcached:
    image: memcached:alpine
    ports:
      - "11211"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai  

  beanstalkd:
    image: schickling/beanstalkd:latest
    ports:
      - "11300"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai  

  db:
    image: mysql:8
    volumes:
     - ./data/database:/var/lib/mysql
    networks:
     - my-web
    environment:
     - MYSQL_ROOT_PASSWORD=root

  web:
    image: wushunyi/nginx-php7-fpm:latest
    ports:
      - 18080:80
    networks:
      - my-web
    depends_on:
      - db
      - redis
      - memcached
      - beanstalkd
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .docker_env_file
    volumes:
      - ./conf/supervisord/supervisord.conf:/etc/supervisord.conf
      - ./conf/supervisord/conf.d:/etc/supervisor/conf.d
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - /Users/wushunyi/dev/test/docker/laravel/laravel-app:/app
      - /Users/wushunyi/dev/test/docker/laravel/laravel-app/nginx.conf:/etc/nginx/sites-enabled/default.conf

networks:
  my-web:

